name: pokedex
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_serializable: ^6.1.1
  json_annotation: ^4.4.0
  build_runner: ^2.1.5
  retrofit: ^3.0.0
  retrofit_generator: ^3.0.0+2
  dio: ^4.0.4
  freezed: ^1.1.0
  freezed_annotation: ^1.1.0
  flutter_hooks: ^0.18.1
  hooks_riverpod: ^1.0.2
  state_notifier: ^0.7.1
  google_fonts: ^2.1.0
  basic_utils: ^3.9.3
  logger: ^1.1.0
  auto_route: ^3.2.0
  auto_route_generator: ^3.2.0
  flutter_svg: ^1.0.0
  cupertino_icons: ^1.0.2
  collection: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
